# Site Author
minimal_mistakes_skin: "default"
# Site Settings
locale: "en-US"
title: "&n00b's archive"
name: "n00b"
description: "n00b's archive"
breadcrumbs: true
words_per_minute: 200
comments:
  provider: giscus
  giscus:
    repo_name: "jjajjajja/jjajjajja.github.io"
    repo_id: "R_kgDOHTpUVQ"
    category_name: "Comments"
    category_id: "DIC_kwDOHTpUVc4CPCt6"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"

# search
search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: lunr # lunr (default), algolia, google

# SEO Related
google_site_verification: W0x_TTUWCTNEMTxgCbGfvXtHxTpfF4voOd704JQ6q7c

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title
paginate: 5
paginate_path: /page:num/
timezone: Asia/Seoul

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: false
      related: false
